import React,{useState}from'react';import{createRoot}from'react-dom/client';import{Plus,Minus,X,ShoppingBag,ArrowRight}from'lucide-react';import'./style.css';
const products=[
{id:1,cat:'Pollo frito',name:'Crujiente Chucky',desc:'Pollo frito dorado, crujiente y recién hecho.',price:7990,img:'https://images.unsplash.com/photo-1626645738196-c2a7c87a8f58?auto=format&fit=crop&w=900&q=85'},
{id:2,cat:'Pollo frito',name:'Balde Chucky',desc:'Piezas de pollo crujiente para compartir.',price:12990,img:'https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=900&q=85'},
{id:3,cat:'Sushi',name:'Roll Chucky',desc:'Roll de la casa, fresco, cremoso y hecho al momento.',price:6990,img:'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=900&q=85'},
{id:4,cat:'Sushi',name:'Roll Crocante',desc:'Roll crocante con salsa de la casa.',price:7490,img:'https://images.unsplash.com/photo-1617196034796-73dfa7b1fd56?auto=format&fit=crop&w=900&q=85'},
{id:5,cat:'Salsas',name:'Salsa Chucky',desc:'El toque final para acompañar tu pedido.',price:800,img:'https://images.unsplash.com/photo-1472476443507-c7a5948772fc?auto=format&fit=crop&w=900&q=85'},
{id:6,cat:'Bebidas',name:'Bebida',desc:'Elige entre los sabores disponibles.',price:2000,img:'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=900&q=85'}
];
const menuCats=['Pollo frito','Sushi','Salsas','Bebidas'];
const money=n=>'$'+n.toLocaleString('es-CL');
function App(){const[view,setView]=useState('home'),[cat,setCat]=useState('Pollo frito'),[cart,setCart]=useState({}),[open,setOpen]=useState(false);const add=id=>setCart(c=>({...c,[id]:(c[id]||0)+1}));const sub=id=>setCart(c=>({...c,[id]:Math.max(0,(c[id]||0)-1)}));const count=Object.values(cart).reduce((a,b)=>a+b,0),total=products.reduce((s,p)=>s+(cart[p.id]||0)*p.price,0);const go=c=>{setCat(c);setView('menu');scrollTo(0,0)};
return <div className="site"><header><button className="word" onClick={()=>setView('menu')}>MENÚ</button><a href="#about">NOSOTROS</a><a href="#where">UBICACIÓN</a><button className="logo" onClick={()=>{setView('home');scrollTo(0,0)}}>'ONDE EL<br/>CHUCKY</button><a href="#contact">CONTACTO</a><button className="order" onClick={()=>setOpen(true)}>HAZ TU PEDIDO {count>0&&<b>{count}</b>}</button></header>
{view==='home'?<><section className="hero"><div className="shade"/><div className="heroCopy"><h1>POLLO FRITO.<br/>SUSHI.<br/>UN SOLO PLAN.</h1><i/><p>DOS ANTOJOS.<br/>UNA SOLA PARADA.<br/>SIEMPRE CHUCKY.</p></div><div className="sidecats">POLLO FRITO<br/>SUSHI<br/>SALSAS<br/>BEBIDAS</div><div className="scroll">SCROLL ↓</div></section>
<section className="formalIdentity" id="about"><div className="formalEyebrow">POLLO FRITO · SUSHI · SAN JAVIER</div><div className="formalName"><span>'ONDE EL</span><strong>CHUCKY</strong></div><p>Dos antojos. Una misma casa.<br/>Hecho para volver.</p></section>
<section className="feature chicken"><div><h3>POLLO FRITO</h3><p>CRUJIENTE, DORADO, RECIÉN HECHO.</p><button onClick={()=>go('Pollo frito')}>VER MENÚ <ArrowRight/></button></div><em>HECHO<br/>PA' MATAR<br/>EL HAMBRE.</em></section>
<section className="grill sushiFeature"><div className="grillNumber">02</div><div className="grillNote">FRESCO.<br/>CROCANTE.<br/>HECHO<br/>AL MOMENTO.</div><div className="grillCaption">SUSHI · ROLLS · SABOR</div></section>
<section className="categoryShow" id="menu"><div className="categoryTitle"><h3>NUESTRO MENÚ</h3><span>POLLO FRITO / SUSHI / SALSAS / BEBIDAS</span></div><div className="categoryCards">{[['Pollo frito','/pollo-frito-png.png'],['Sushi','/sushi.png'],['Salsas','/salsas.png'],['Bebidas','/bebidas.png']].map(([c,img])=><button onClick={()=>go(c)}><img src={img}/><b>{c.toUpperCase()}</b><small>VER →</small></button>)}</div></section><section className="must"><div className="mustIntro"><h3>LOS<br/>INFALTABLES</h3><p>POLLO O SUSHI.<br/>TÚ ELIGES EL PLAN.</p></div>{products.slice(0,3).map(p=><article><img src={p.img}/><div><h4>{p.name}</h4><p>{p.desc}</p><footer><b>{money(p.price)}</b><button onClick={()=>add(p.id)}><Plus/></button></footer></div></article>)}</section>
<section className="where" id="where"><div className="wherePic"><strong>“AQUÍ TAMBIÉN<br/>SE VIVEN<br/>BUENAS HISTORIAS”</strong></div><div className="whereCopy"><small>TE ESPERAMOS</small><h3>EN LA CALLE.<br/>CERCA DEL ANTOJO.</h3><p>San Javier, Chile · ubicación referencial para el boceto.</p><button>CÓMO LLEGAR →</button></div><div className="paper"><b>'ONDE<br/>EL CHUCKY</b><span>GRACIAS<br/>POR SER PARTE<br/>DE ESTO.</span></div></section></>:<section className="shop"><button className="back" onClick={()=>setView('home')}>← VOLVER AL INICIO</button><p className="kicker">NUESTRO MENÚ</p><h2>ELIGE TU<br/>ANTOJO.</h2><nav>{menuCats.map(c=><button className={cat===c?'active':''} onClick={()=>setCat(c)}>{c}</button>)}</nav><div className="products">{products.filter(p=>p.cat===cat).map(p=><article><img src={p.img}/><div><small>{p.cat}</small><h3>{p.name}</h3><p>{p.desc}</p><footer><b>{money(p.price)}</b><button onClick={()=>add(p.id)}><Plus/> AGREGAR</button></footer></div></article>)}{!products.some(p=>p.cat===cat)&&<div className="empty">Pronto agregamos productos de {cat}.<br/><small>Este sigue siendo nuestro boceto.</small></div>}</div></section>}
<footer className="foot" id="contact"><b>'ONDE EL CHUCKY</b><span>POLLO FRITO · SUSHI · SAN JAVIER</span></footer>
{count>0&&<button className="floating" onClick={()=>setOpen(true)}><ShoppingBag/><span>{count} PRODUCTO{count!==1?'S':''}</span><b>{money(total)}</b></button>}
{open&&<div className="overlay" onClick={()=>setOpen(false)}><aside onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setOpen(false)}><X/></button><small>TU PEDIDO</small><h2>CASI ESTÁ.</h2>{count===0?<p className="emptycart">Todavía no agregas nada.</p>:products.filter(p=>cart[p.id]).map(p=><div className="line"><img src={p.img}/><div><b>{p.name}</b><span>{money(p.price)}</span></div><div className="qty"><button onClick={()=>sub(p.id)}><Minus/></button>{cart[p.id]}<button onClick={()=>add(p.id)}><Plus/></button></div></div>)}<div className="total"><span>TOTAL</span><b>{money(total)}</b></div><button className="finish">CONTINUAR PEDIDO →</button><p className="prototype">Checkout de demostración. Lo conectamos cuando aprobemos el diseño.</p></aside></div>}</div>}
createRoot(document.getElementById('root')).render(<App/>);