import React,{useState}from'react';import{createRoot}from'react-dom/client';import{Plus,Minus,X,ShoppingBag,ArrowRight}from'lucide-react';import'./style.css';
const products=[{id:1,cat:'Hamburguesas',name:'La Callejera',desc:'Doble carne, cheddar, tocino, cebolla caramelizada y salsa de la casa.',price:7900,img:'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=900&q=85'},{id:2,cat:'Hamburguesas',name:'La Chucky',desc:'Carne smash, queso fundido, pepinillos y salsa especial.',price:6900,img:'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=900&q=85'},{id:3,cat:'Completos',name:'El Italiano',desc:'Vienesa, tomate, palta y mayo casera.',price:4900,img:'https://images.unsplash.com/photo-1612392062631-94dd858cba88?auto=format&fit=crop&w=900&q=85'},{id:4,cat:'Papas',name:'Papas del Barrio',desc:'Papas crujientes, cheddar, carne y cebollín.',price:5900,img:'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=900&q=85'}];
const money=n=>'$'+n.toLocaleString('es-CL');
function App(){const[view,setView]=useState('home'),[cat,setCat]=useState('Hamburguesas'),[cart,setCart]=useState({}),[open,setOpen]=useState(false);const add=id=>setCart(c=>({...c,[id]:(c[id]||0)+1}));const sub=id=>setCart(c=>({...c,[id]:Math.max(0,(c[id]||0)-1)}));const count=Object.values(cart).reduce((a,b)=>a+b,0),total=products.reduce((s,p)=>s+(cart[p.id]||0)*p.price,0);const go=c=>{setCat(c);setView('menu');scrollTo(0,0)};
return <div className="site"><header><button className="word" onClick={()=>setView('menu')}>MENÚ</button><a href="#about">NOSOTROS</a><a href="#where">UBICACIÓN</a><button className="logo" onClick={()=>{setView('home');scrollTo(0,0)}}>'ONDE EL<br/>CHUCKY</button><a href="#contact">CONTACTO</a><button className="order" onClick={()=>setOpen(true)}>HAZ TU PEDIDO {count>0&&<b>{count}</b>}</button></header>
{view==='home'?<><section className="hero"><div className="shade"/><div className="heroCopy"><h1>MÁS<br/>QUE COMIDA,<br/>ES UN PLAN.</h1><i/><p>BUENA COMIDA.<br/>MALAS DECISIONES.<br/>SIEMPRE AQUÍ.</p></div><div className="sidecats">SANGUCHERÍA<br/>COMPLETOS<br/>PAPAS<br/>BEBIDAS<br/>Y MÁS.</div><div className="scroll">SCROLL ↓</div></section>
<section className="storyStrip sauceSection" id="about"><div className="sauceSide left">HECHO<br/>EN LA CALLE,<br/>COMO TIENE<br/>QUE SER.<i/></div><div className="sauceLogo"><span className="grain g1">✦</span><span className="grain g2">•</span><span className="grain g3">✦</span><h2 aria-label="'Onde el Chucky"><span className="sauceWord top"><b style={{'--i':0}}>'</b><b style={{'--i':1}}>O</b><b style={{'--i':2}}>N</b><b style={{'--i':3}}>D</b><b style={{'--i':4}}>E</b></span><span className="sauceWord mid"><b style={{'--i':5}}>E</b><b style={{'--i':6}}>L</b></span><span className="sauceWord bottom"><b style={{'--i':7}}>C</b><b style={{'--i':8}}>H</b><b style={{'--i':9}}>U</b><b style={{'--i':10}}>C</b><b style={{'--i':11}}>K</b><b style={{'--i':12}}>Y</b></span></h2><svg className="sauceSwipe" viewBox="0 0 420 42" aria-hidden="true"><path pathLength="1" d="M8 29 C95 5 208 8 410 17 C326 21 191 26 33 35" /></svg></div><div className="sauceSide right">COMIDA<br/>REAL.<br/>GENTE<br/>REAL.<i/></div></section>
<section className="feature burger"><div><h3>HAMBURGUESAS</h3><p>CLÁSICAS, PERO MEJORES.</p><button onClick={()=>go('Hamburguesas')}>VER MENÚ <ArrowRight/></button></div><em>HECHO<br/>PA' MATAR<br/>EL HAMBRE.</em></section>
<section className="grill"><div className="grillNote">EL SABOR<br/>TAMBIÉN<br/>ES PARTE<br/>DEL PLAN.</div></section>
<section className="categoryShow"><div className="categoryTitle"><h3>NUESTRO MENÚ</h3><span>HAMBURGUESAS / COMPLETOS / PAPAS / BEBIDAS / PROMOS</span></div><div className="categoryCards">{[['Hamburguesas','https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=700&q=85'],['Completos','https://images.unsplash.com/photo-1612392062631-94dd858cba88?auto=format&fit=crop&w=700&q=85'],['Papas','https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=700&q=85'],['Bebidas','https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=700&q=85'],['Promos','https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?auto=format&fit=crop&w=700&q=85']].map(([c,img])=><button onClick={()=>go(c)}><img src={img}/><b>{c.toUpperCase()}</b><small>VER →</small></button>)}</div></section><section className="must"><div className="mustIntro"><h3>LOS<br/>INFALTABLES</h3><p>DISTINTOS PLANES.<br/>MISMO SABOR.</p></div>{products.slice(0,3).map(p=><article><img src={p.img}/><div><h4>{p.name}</h4><p>{p.desc}</p><footer><b>{money(p.price)}</b><button onClick={()=>add(p.id)}><Plus/></button></footer></div></article>)}</section>
<section className="where" id="where"><div className="wherePic"><strong>“AQUÍ TAMBIÉN<br/>SE VIVEN<br/>BUENAS HISTORIAS”</strong></div><div className="whereCopy"><small>TE ESPERAMOS</small><h3>EN LA CALLE.<br/>CERCA DEL ANTOJO.</h3><p>San Javier, Chile · ubicación referencial para el boceto.</p><button>CÓMO LLEGAR →</button></div><div className="paper"><b>'ONDE<br/>EL CHUCKY</b><span>GRACIAS<br/>POR SER PARTE<br/>DE ESTO.</span></div></section></>:<section className="shop"><button className="back" onClick={()=>setView('home')}>← VOLVER AL INICIO</button><p className="kicker">NUESTRO MENÚ</p><h2>ELIGE TU<br/>ANTOJO.</h2><nav>{['Hamburguesas','Completos','Papas','Bebidas','Promos'].map(c=><button className={cat===c?'active':''} onClick={()=>setCat(c)}>{c}</button>)}</nav><div className="products">{products.filter(p=>p.cat===cat).map(p=><article><img src={p.img}/><div><small>{p.cat}</small><h3>{p.name}</h3><p>{p.desc}</p><footer><b>{money(p.price)}</b><button onClick={()=>add(p.id)}><Plus/> AGREGAR</button></footer></div></article>)}{!products.some(p=>p.cat===cat)&&<div className="empty">Pronto agregamos productos de {cat}.<br/><small>Este sigue siendo nuestro boceto.</small></div>}</div></section>}
<footer className="foot" id="contact"><b>'ONDE EL CHUCKY</b><span>FOODTRUCK · DESDE LA CALLE PARA LA GENTE</span></footer>
{count>0&&<button className="floating" onClick={()=>setOpen(true)}><ShoppingBag/><span>{count} PRODUCTO{count!==1?'S':''}</span><b>{money(total)}</b></button>}
{open&&<div className="overlay" onClick={()=>setOpen(false)}><aside onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setOpen(false)}><X/></button><small>TU PEDIDO</small><h2>CASI ESTÁ.</h2>{count===0?<p className="emptycart">Todavía no agregas nada.</p>:products.filter(p=>cart[p.id]).map(p=><div className="line"><img src={p.img}/><div><b>{p.name}</b><span>{money(p.price)}</span></div><div className="qty"><button onClick={()=>sub(p.id)}><Minus/></button>{cart[p.id]}<button onClick={()=>add(p.id)}><Plus/></button></div></div>)}<div className="total"><span>TOTAL</span><b>{money(total)}</b></div><button className="finish">CONTINUAR PEDIDO →</button><p className="prototype">Checkout de demostración. Lo conectamos cuando aprobemos el diseño.</p></aside></div>}</div>}
createRoot(document.getElementById('root')).render(<App/>);